services:
 sql-weather-api:
  image: mcr.microsoft.com/mssql/server:2022-latest
  container_name: "sql-weather-api"
  environment:
    SA_PASSWORD: "Ma921919"
    ACCEPT_EULA: "Y"
  ports:
    - "8001:1433"

 mywebapi:
  image: mohamedashraf19/mywebapi
  container_name: "mywebapi"
  build:
    context: .
    dockerfile: MyWebAPI\dockerfile
  depends_on:
    - sql-weather-api
  ports:  
    - "8000:80"
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__dbcontext=Data Source=sql-weather-api; Initial Catalog=weatherDb; User ID=sa; Password=Ma921919;TrustServerCertificate=True;